package com.bemily.messenger.smileme.domain.model

import com.olivia.architecturetemplate.R
import com.olivia.architecturetemplate.domain.model.SmileMeSticker


/**
 * Bemily
 * 스마일미 관련 스티커, 필터 데이터 정의
 * @author HANSANGJUN
 * @version 1.0.0
 * @since 2021-07-22
 **/
object SmileMeStore {

    val stickers = listOf(
        SmileMeDecor(
            SmileMeSticker.LOVE_SHOT.ordinal,
            R.string.smile_me_love_shot,
            R.drawable.smile_me_love_shot_thumb
        ),
        SmileMeDecor(
            SmileMeSticker.PRESENT.ordinal,
            R.string.smile_me_present,
            R.drawable.smile_me_present_thumb
        ),
        SmileMeDecor(
            SmileMeSticker.BF_LOVE.ordinal,
            R.string.smile_me_bf_love,
            R.drawable.smile_me_bf_love_thumb
        ),
        SmileMeDecor(
            SmileMeSticker.CHEER_LOVE.ordinal,
            R.string.smile_me_cheer_love,
            R.drawable.smile_me_cheer_love_thumb
        ),
        SmileMeDecor(
            SmileMeSticker.LIKE_BOMB.ordinal,
            R.string.smile_me_like_bomb,
            R.drawable.smile_me_like_bomb_thumb
        ),

        SmileMeDecor(
            SmileMeSticker.NEW_YEAR_SUNRISE.ordinal,
            R.string.smile_me_new_year_sunrise,
            R.drawable.smile_me_new_year_sunrise_thumb
        ),
        SmileMeDecor(
            SmileMeSticker.NEW_YEAR_BOY.ordinal,
            R.string.smile_me_new_year_boy,
            R.drawable.smile_me_new_year_boy_thumb
        ),
        SmileMeDecor(
            SmileMeSticker.NEW_YEAR_GIRL.ordinal,
            R.string.smile_me_new_year_girl,
            R.drawable.smile_me_new_year_girl_thumb
        ),
        SmileMeDecor(
            SmileMeSticker.HAPPY_NEW_YEAR.ordinal,
            R.string.smile_me_happy_new_year,
            R.drawable.smile_me_happy_new_year_thumb
        ),
        SmileMeDecor(
            SmileMeSticker.TIGER_NEW_YEAR.ordinal,
            R.string.smile_me_tiger_new_year,
            R.drawable.smile_me_tiger_new_year_thumb
        ),
        SmileMeDecor(
            SmileMeSticker.FORTUNE_COME.ordinal,
            R.string.smile_me_fortune_come,
            R.drawable.smile_me_fortune_come_thumb
        ),
        SmileMeDecor(
            SmileMeSticker.AGE_DELIVERY.ordinal,
            R.string.smile_me_age_delivery,
            R.drawable.smile_me_age_delivery_thumb
        ),
        SmileMeDecor(
            SmileMeSticker.LEONG.ordinal,
            R.string.smile_me_sticker_leong,
            R.drawable.smile_me_leong_thumb
        ),
        SmileMeDecor(
            SmileMeSticker.LAONG.ordinal,
            R.string.smile_me_sticker_laong,
            R.drawable.smile_me_laong_thumb
        ),
        SmileMeDecor(
            SmileMeSticker.HONEY_JAM.ordinal,
            R.string.smile_me_sticker_honey_jam,
            R.drawable.smile_me_honey_jam_thumb
        ),
        SmileMeDecor(
            SmileMeSticker.COFFEE.ordinal,
            R.string.smile_me_sticker_coffee,
            R.drawable.smile_me_coffee_thumb
        ),
        SmileMeDecor(
            SmileMeSticker.YELLOW_CARD.ordinal,
            R.string.smile_me_sticker_yellow_card,
            R.drawable.smile_me_yellow_card_thumb
        ),
        SmileMeDecor(
            SmileMeSticker.STAMP.ordinal,
            R.string.smile_me_sticker_stamp,
            R.drawable.smile_me_stamp_thumb
        ),
        SmileMeDecor(
            SmileMeSticker.ARROW.ordinal,
            R.string.smile_me_sticker_arrow,
            R.drawable.smile_me_arrow_thumb
        ),
        SmileMeDecor(
            SmileMeSticker.CELEBRATE.ordinal,
            R.string.smile_me_sticker_celebrate,
            R.drawable.smile_me_celebrate_thumb
        ),
        SmileMeDecor(
            SmileMeSticker.CHEERS.ordinal,
            R.string.smile_me_sticker_cheers,
            R.drawable.smile_me_cheers_thumb
        ),
        SmileMeDecor(
            SmileMeSticker.CHEER_UP.ordinal,
            R.string.smile_me_sticker_cheer_up,
            R.drawable.smile_me_cheer_up_thumb
        ),
        SmileMeDecor(
            SmileMeSticker.TIRED.ordinal,
            R.string.smile_me_sticker_tired,
            R.drawable.smile_me_tired_thumb
        ),
        SmileMeDecor(
            SmileMeSticker.SICK.ordinal,
            R.string.smile_me_sticker_sick,
            R.drawable.smile_me_sick_thumb
        ),
        SmileMeDecor(
            SmileMeSticker.EAT.ordinal,
            R.string.smile_me_sticker_eat,
            R.drawable.smile_me_eat_thumb
        ),
        SmileMeDecor(
            SmileMeSticker.SHOOT.ordinal,
            R.string.smile_me_sticker_shoot,
            R.drawable.smile_me_shoot_thumb
        ),
        SmileMeDecor(
            SmileMeSticker.RAINY.ordinal,
            R.string.smile_me_sticker_rainy,
            R.drawable.smile_me_rainy_thumb
        ),
        SmileMeDecor(
            SmileMeSticker.DIZZY.ordinal,
            R.string.smile_me_sticker_dizzy,
            R.drawable.smile_me_dizzy_thumb
        ),
        SmileMeDecor(
            SmileMeSticker.COMING.ordinal,
            R.string.smile_me_sticker_coming,
            R.drawable.smile_me_coming_thumb
        ),
        SmileMeDecor(
            SmileMeSticker.GOING.ordinal,
            R.string.smile_me_sticker_going,
            R.drawable.smile_me_going_thumb
        ),
        SmileMeDecor(
            SmileMeSticker.COLD.ordinal,
            R.string.smile_me_sticker_cold,
            R.drawable.smile_me_cold_thumb
        ),
        SmileMeDecor(
            SmileMeSticker.HOT.ordinal,
            R.string.smile_me_sticker_hot,
            R.drawable.smile_me_hot_thumb
        ),
        SmileMeDecor(
            SmileMeSticker.SCARED.ordinal,
            R.string.smile_me_sticker_scared,
            R.drawable.smile_me_scared_thumb
        ),
        SmileMeDecor(
            SmileMeSticker.HI.ordinal,
            R.string.smile_me_sticker_hi,
            R.drawable.smile_me_hi_thumb
        ),
        SmileMeDecor(
            SmileMeSticker.SORRY.ordinal,
            R.string.smile_me_sticker_sorry,
            R.drawable.smile_me_sorry_thumb
        ),
        SmileMeDecor(
            SmileMeSticker.OK.ordinal,
            R.string.smile_me_sticker_ok,
            R.drawable.smile_me_ok_thumb
        ),
        SmileMeDecor(
            SmileMeSticker.SURPRISE.ordinal,
            R.string.smile_me_sticker_surprise,
            R.drawable.smile_me_surprise_thumb
        ),
        SmileMeDecor(
            SmileMeSticker.LAUGH.ordinal,
            R.string.smile_me_sticker_laugh,
            R.drawable.smile_me_laugh_thumb
        ),
        SmileMeDecor(
            SmileMeSticker.CALL_ME.ordinal,
            R.string.smile_me_sticker_call_me,
            R.drawable.smile_me_call_me_thumb
        ),
        SmileMeDecor(
            SmileMeSticker.DISTRESS.ordinal,
            R.string.smile_me_sticker_distress,
            R.drawable.smile_me_distress_thumb
        ),
        SmileMeDecor(
            SmileMeSticker.THANKS.ordinal,
            R.string.smile_me_sticker_thanks,
            R.drawable.smile_me_thanks_thumb
        ),
        SmileMeDecor(
            SmileMeSticker.ANGRY.ordinal,
            R.string.smile_me_sticker_angry,
            R.drawable.smile_me_angry_thumb
        ),
        SmileMeDecor(
            SmileMeSticker.STARING.ordinal,
            R.string.smile_me_sticker_staring,
            R.drawable.smile_me_staring_thumb
        ),
        SmileMeDecor(
            SmileMeSticker.CONGRATULATION.ordinal,
            R.string.smile_me_sticker_congratulation,
            R.drawable.smile_me_congratulation_thumb
        ),
        SmileMeDecor(
            SmileMeSticker.QUESTION.ordinal,
            R.string.smile_me_sticker_question,
            R.drawable.smile_me_question_thumb
        ),
        SmileMeDecor(
            SmileMeSticker.TOUCHED.ordinal,
            R.string.smile_me_sticker_touched,
            R.drawable.smile_me_touched_thumb
        ),
        SmileMeDecor(
            SmileMeSticker.PLEASE.ordinal,
            R.string.smile_me_sticker_please,
            R.drawable.smile_me_please_thumb
        ),
        SmileMeDecor(
            SmileMeSticker.GLOOM.ordinal,
            R.string.smile_me_sticker_gloom,
            R.drawable.smile_me_gloom_thumb
        ),
        SmileMeDecor(
            SmileMeSticker.NO.ordinal,
            R.string.smile_me_sticker_no,
            R.drawable.smile_me_no_thumb
        ),
        SmileMeDecor(
            SmileMeSticker.FIGHTING.ordinal,
            R.string.smile_me_sticker_fighting,
            R.drawable.smile_me_fighting_thumb
        ),
        SmileMeDecor(
            SmileMeSticker.LOVE.ordinal,
            R.string.smile_me_sticker_love,
            R.drawable.smile_me_love_thumb
        ),
        SmileMeDecor(
            SmileMeSticker.SLEEP.ordinal,
            R.string.smile_me_sticker_sleep,
            R.drawable.smile_me_sleep_thumb
        ),
        SmileMeDecor(
            SmileMeSticker.BEST.ordinal,
            R.string.smile_me_sticker_best,
            R.drawable.smile_me_best_thumb
        )
    )

    val filters = listOf(
        SmileMeDecor(
            SmileMeFilter.NONE.ordinal,
            R.string.smile_me_filter_none,
            R.drawable.smile_me_none_thumb
        ),
        SmileMeDecor(
            SmileMeFilter.CONTRAST.ordinal,
            R.string.smile_me_filter_contrast,
            R.drawable.smile_me_contrast_thumb
        ),
        SmileMeDecor(
            SmileMeFilter.MONO.ordinal,
            R.string.smile_me_filter_mono,
            R.drawable.smile_me_mono_thumb
        ),
        SmileMeDecor(
            SmileMeFilter.SEPIA.ordinal,
            R.string.smile_me_filter_sepia,
            R.drawable.smile_me_sepia_thumb
        ),
        SmileMeDecor(
            SmileMeFilter.WARM.ordinal,
            R.string.smile_me_filter_warm,
            R.drawable.smile_me_warm_thumb
        ),
        SmileMeDecor(
            SmileMeFilter.COOL.ordinal,
            R.string.smile_me_filter_cool,
            R.drawable.smile_me_cool_thumb
        ),
    )

}